/**
 * Programmatically-generated starter LUTs for the `lut-3d` effect.
 *
 * Each built-in look is a pure `(r, g, b) -> [r, g, b]` color transform baked
 * into Adobe/Iridas `.cube` text by `buildCubeText`, then registered through
 * the exact same `registerLutFromCubeText` path a user upload takes (see
 * `lut-registry.ts`). Everything here is generated by us at module load — no
 * third-party LUT files are bundled (their licenses are murky), so there is
 * nothing to attribute and nothing to redistribute.
 */

/** A pure per-pixel color transform in normalized [0,1] RGB space. */
export type LutTransform = (
	r: number,
	g: number,
	b: number,
) => [number, number, number];

/**
 * Grid resolution for generated built-ins. All the looks below are smooth
 * functions, so 17^3 samples plus the shader's trilinear interpolation
 * reproduces them with no visible banding while keeping module-load parse
 * cost and texture memory small.
 */
export const BUILTIN_LUT_SIZE = 17;

function clamp01(value: number): number {
	return Math.min(1, Math.max(0, value));
}

/** Rec. 709 luma — used by the mono + faded looks. */
function luma(r: number, g: number, b: number): number {
	return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** Classic smoothstep S-curve, used to add contrast without clipping. */
function sCurve(x: number): number {
	return x * x * (3 - 2 * x);
}

function mix(a: number, b: number, t: number): number {
	return a + (b - a) * t;
}

/**
 * Bakes a color transform into `.cube` file text (red fastest-varying, as the
 * spec requires). Kept generic so future looks — or a "download this LUT"
 * export — can reuse it.
 */
export function buildCubeText({
	title,
	size,
	transform,
}: {
	title: string;
	size: number;
	transform: LutTransform;
}): string {
	const lines: string[] = [`TITLE "${title}"`, `LUT_3D_SIZE ${size}`];
	const max = size - 1;
	for (let b = 0; b < size; b++) {
		for (let g = 0; g < size; g++) {
			for (let r = 0; r < size; r++) {
				const [or, og, ob] = transform(r / max, g / max, b / max);
				lines.push(
					`${clamp01(or).toFixed(6)} ${clamp01(og).toFixed(6)} ${clamp01(ob).toFixed(6)}`,
				);
			}
		}
	}
	return lines.join("\n");
}

export interface BuiltinLutLook {
	id: string;
	label: string;
	transform: LutTransform;
}

/**
 * The starter looks. Ids are namespaced `builtin-*` so they can never collide
 * with uploaded presets (`user-*`) or the identity preset.
 */
export const BUILTIN_LUT_LOOKS: readonly BuiltinLutLook[] = [
	{
		id: "builtin-warm",
		label: "Warm",
		// Golden-hour push: lift red, gently mute blue.
		transform: (r, g, b) => [r * 1.06 + 0.02, g * 1.01, b * 0.9],
	},
	{
		id: "builtin-cool",
		label: "Cool",
		// Arctic push: the mirror of Warm.
		transform: (r, g, b) => [r * 0.9, g * 1.01, b * 1.06 + 0.02],
	},
	{
		id: "builtin-high-contrast",
		label: "High Contrast",
		// Blend each channel 70% toward an S-curve — punchy but unclipped.
		transform: (r, g, b) => [
			mix(r, sCurve(r), 0.7),
			mix(g, sCurve(g), 0.7),
			mix(b, sCurve(b), 0.7),
		],
	},
	{
		id: "builtin-mono",
		label: "Black & White",
		transform: (r, g, b) => {
			const y = luma(r, g, b);
			return [y, y, y];
		},
	},
	{
		id: "builtin-faded-film",
		label: "Faded Film",
		// Lifted blacks, compressed highlights, 25% desaturation, warm bias.
		transform: (r, g, b) => {
			const y = luma(r, g, b);
			const fade = (x: number) => 0.06 + x * 0.88;
			return [
				fade(mix(r, y, 0.25)) * 1.03,
				fade(mix(g, y, 0.25)),
				fade(mix(b, y, 0.25)) * 0.96,
			];
		},
	},
];

/** `.cube` text for every built-in look, ready for `registerLutFromCubeText`. */
export function generateBuiltinLutCubes(): Array<{
	id: string;
	label: string;
	cubeText: string;
}> {
	return BUILTIN_LUT_LOOKS.map(({ id, label, transform }) => ({
		id,
		label,
		cubeText: buildCubeText({
			title: label,
			size: BUILTIN_LUT_SIZE,
			transform,
		}),
	}));
}
